line-length = 100
target-version = "py313"

extend-exclude = [
  ".dagger",
  ".venv",
  "venv",
  "__pycache__",
]

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "ASYNC",
]

[format]
quote-style = "double"
indent-style = "space"
